modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="potionbundles"
version="${file.jarVersion}"
displayName="Potion Bundles"
displayURL="http://www.curseforge.com/minecraft/mc-mods/potion-bundles"
authors="IchHabeHunger54, Minecraftschurli"
description='''
Adds "potion bundles", a type of stackable potions inspired by Ars Magica: Legacy.
'''
[[dependencies.potionbundles]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.potionbundles]]
modId="minecraft"
versionRange="[1.16.5]"
mandatory=true
ordering="NONE"
side="BOTH"
